stages:
  - build_macos
  - build_ios
  - test_ios
  - test_macos

build_macos:
  stage: build_macos
  script:
    - swift build
  tags:
    - xcode
    - macos

build_ios:
  stage: build_ios
  script:
   - xcodebuild -scheme Carpaccio iphonesimulator -destination 'platform=iOS Simulator,name=iPhone XS,OS=12.1'
  tags:
    - xcode
    - macos

test_macos:
  stage: test_macos
  script:
   - xcodebuild -workspace Carpaccio.xcworkspace -scheme Carpaccio-OSX clean test | xcpretty
  dependencies:
    - build_macos
  tags:
    - xcode
    - macos

test_ios:
  stage: test_ios
  script:
    - xcodebuild -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=12.1' -workspace Carpaccio.xcworkspace -scheme Carpaccio-iOS clean test | xcpretty
  dependencies:
    - build_ios
  tags:
    - xcode
    - macos
